detailComment/urls.py
from django.urls import path
from . import views

app_name = "detailComment"

urlpatterns = [
    path('<str:namaResep>/', views.detail, name='detail'),
]

homepage/urls.py
from django.urls import path
from . import views

app_name = "homepage"
urlpatterns = [
    path('', views.home, name='home'),
]

kategori/urls.py
from django.urls import path
from . import views

app_name = 'kategori'

urlpatterns = [
    path('', views.kategori, name="kategori"),
    path('<str:nama>/', views.spesifik, name="kategori_spesifik"),
    ]

makanminum/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('homepage.urls')),
    path('detail/', include('detailComment.urls')),
    path('resep_form/', include('tambahupdate.urls')),
    path('misc/', include('kritiksaran.urls')),
    path('kategori/', include('kategori.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

tambahupdate/urls.py
from django.urls import path
from . import views

app_name = 'tambahupdate'

urlpatterns = [
    path('tulis/', views.tulis, name="tulis"),
    path('perbarui/<int:pk>/', views.perbarui, name="perbarui"),
]

detailComment/models.py
from django.db import models
from django.db.models.deletion import CASCADE
from django.db.models.fields.related import ForeignKey
from tambahupdate.models import Resep

# Create your models here.


class Comment(models.Model):
    resep = models.ForeignKey(Resep, on_delete=models.CASCADE)
    komentar = models.TextField()
    created_at = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.komentar

detailComment/forms.py
from django import forms
from .models import Comment


class CommentForm(forms.ModelForm):
    class Meta():
        model = Comment
        fields = ['komentar']
        widgets = {
            'komentar': forms.Textarea(attrs={'rows': 8, 'cols': 40}),
        }
        labels = {
            'komentar': "Berikan komentar untuk resep ini:",
        }

detailComment/views.py
from django.http import response, HttpResponseRedirect
from django.shortcuts import render, redirect
from django.contrib import messages
from .models import Comment
from tambahupdate.models import Resep
from kategori.models import Kategori
from .forms import CommentForm

# Create your views here.

def detail(request, namaResep):
    resep = Resep.objects.get(nama=namaResep)
    form = CommentForm(request.POST or None)
    if form.is_valid():
        komen = request.POST['komentar']
        resep.comment_set.create(komentar=komen)
        messages.success(request, 'Komentar berhasil ditambahkan!')
        return redirect(f'/detail/{resep.nama}/')
    response = {
        "form": form,
        "resep": resep,
    }
    return render(request, 'detail.html', response)

detailComment/templates/detail.html
{% extends 'base.html' %}
{% load static %}
{% block head %}
<link rel="stylesheet" href="{% static 'detail.css' %}">
{% endblock %}
{% load crispy_forms_tags %}
{% block content %}
<div class="container mt-4 mb-4 pb-2 pt-2">
    <div class="col-lg-8" style="margin: auto;">
        {% if messages %}
            {% for message in messages %}
                {% if message.level == DEFAULT_MESSAGE_LEVELS.SUCCESS %}
                    <div class="alert alert-success" role="alert" style=>
                        {{ message }}
                    </div>
                {% endif %}
            {% endfor %}
        {% endif %}
        {% if form.errors %}
            {% for field in form %}
                {% for error in field.errors %}
                    <div class="alert alert-danger">
                        <strong>{{ error|escape }}</strong>
                    </div>
                {% endfor %}
            {% endfor %}
            {% for error in form.non_field_errors %}
                <div class="alert alert-danger">
                    <strong>{{ error|escape }}</strong>
                </div>
            {% endfor %}
        {% endif %}
        <a href="{% url 'kategori:kategori' %}" class="btn btn-success mb-4">< Kembali</a>
        <br>
        {% if resep.foto %}
            <img src="{{ resep.foto.url }}" alt="{{ resep.nama }}" class="foto img-fluid">
        {% else %}
            <img src="{% static 'NoPhoto.jpg' %}" alt="Resep tanpa foto" class="foto img-fluid">
        {% endif %}
        <br>
        <p class="nama">{{ resep.nama }}</p>
        <p class="text-center durasi-porsi">
        <img src="{% static 'stopwatch.png' %}" alt="Durasi">
        {{ resep.durasi }}
        <img src=" {% static 'fryingpan.png' %}" alt="Porsi">
        {{ resep.porsi }}</p>
        <p>{{ resep.deskripsi }}</p>
        <hr>
        <h3 class="titlebl"> Bahan - bahan </h3>
        <p class="descbl">{{ resep.bahan|linebreaks }}</p>
        <hr>
        <h3 class="titlebl"> Langkah - langkah </h3>
        <p class="descbl">{{ resep.langkah|linebreaks }}</p>
        <a href="{% url 'tambahupdate:perbarui' resep.id %}" class="btn btn-success col-lg-12 mt-4 mb-4">Perbarui</a>
    </div>
</div>
<div class="container-fluid" style="background-color: #e0e0e0;">
    <div class="container" style="padding-top: 3rem; padding-bottom: 3rem;">
        <div class="col-lg-8" style="margin: auto;">
            <form method="POST" enctype="multipart/form-data" style="margin-bottom: 2rem;"> {% csrf_token %}
                {{ form.komentar|as_crispy_field }}
                <button class="btn btn-success col-lg-12 mt-4 mb-4" type="submit">Kirim Komentar</button>
            </form>
            <h5>Komentar</h5>
            <br>
            {% if resep.comment_set.all %}
                {% for komeng in resep.comment_set.all %}
                    <div class="everycomment">{{ komeng.komentar }}</div>
                {% endfor %}
            {% else %}
            <p>Belum ada komentar.</p>
            {% endif %}
        </div>
    </div>
</div>
{% endblock %}