detailComment/urls.py
from django.urls import path
from . import views

app_name = "detailComment"

urlpatterns = [
    path('<str:namaResep>/', views.detail, name='detail'),
]

homepage/urls.py
from django.urls import path
from . import views

app_name = "homepage"
urlpatterns = [
    path('', views.home, name='home'),
]

kategori/urls.py
from django.urls import path
from . import views

app_name = 'kategori'

urlpatterns = [
    path('', views.kategori, name="kategori"),
    path('<str:nama>/', views.spesifik, name="kategori_spesifik"),
    ]

makanminum/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('homepage.urls')),
    path('detail/', include('detailComment.urls')),
    path('resep_form/', include('tambahupdate.urls')),
    path('misc/', include('kritiksaran.urls')),
    path('kategori/', include('kategori.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

kategori/models.py
from django.db import models
from django.shortcuts import reverse

# Create your models here.
class Kategori(models.Model):
    nama = models.CharField(max_length=25)

    def __str__(self):
        return self.nama

    def get_absolute_url(self):
        return reverse('kategori:kategori_spesifik', args=[self.nama])

kategori/views.py
from django.shortcuts import render,get_object_or_404
from django.http import HttpResponse
from tambahupdate.models import Resep
from .models import Kategori


# Create your views here.
def kategori(request):
    context = {
        'list_resep' : Resep.objects.all().order_by("-id") [:6],
        'list_kategori' : Kategori.objects.all(),
    }
    return render(request, "kategori.html", context)

def spesifik(request, nama):
    context = {
        'kategori' : nama,
        'list_resep_by_kategori' : Resep.objects.filter(kategori = Kategori.objects.get(nama = nama)).order_by("-id")
    }
    return render(request, "kategori_spesifik.html", context)

kategori/templates/kategori.html
{% extends 'base.html' %}
{% load static %}
{% block head %}
<link rel="stylesheet" href="{% static 'kategori.css' %}">
{% endblock %}
{% block content %}
<div class="container mt-5">
    <a href="{% url 'homepage:home' %}" class="btn btn-success"> < Kembali</a>
    <h1 style="text-align: center; padding-bottom: 2rem;">Resep Terbaru</h1>
</div>
<div class="container mt-5 mb-5">
    {% if messages %}
        {% for message in messages %}
            <div class="alert alert-success" style="text-align: center;">{{ message }}</div>
        {% endfor %}
    {% endif %}
    {% if form.errors %}
        {% for field in form %}
            {% for error in field.errors %}
                <div class="alert alert-danger">
                    <strong>{{ error|escape }}</strong>
                </div>
            {% endfor %}
        {% endfor %}
        {% for error in form.non_field_errors %}
            <div class="alert alert-danger">
                <strong>{{ error|escape }}</strong>
            </div>
        {% endfor %}
    {% endif %}
</div>
<div class="col-lg-12">
    <div class="row justify-content-center">
        {% if list_resep %}
            {% for resep in list_resep %}    
                <div class="col-auto mb-3">
                    <a class="link-spesifik" style="color:black" href="{% url 'detailComment:detail' resep.nama %}">
                        <div class="card">
                            {% if resep.foto %}
                                <img class="card-img-top" src="{{ resep.foto.url }}" alt="{{ resep.nama }}">
                            {% else %}
                                <img class="card-img-top" src="{% static 'NoPhoto.jpg' %}" alt="Resep tanpa foto">
                            {% endif %}
                            <div class="card-body" style="text-align: center;">
                                <p class="card-text">{{ resep.nama }}</p>
                            </div>
                        </div>
                    </a>
                </div>
            {% endfor %}
        {% else %}
                <br><br><br>
                <h5>Belum ada resep yang tersedia.</h5>
                <br><br><br>
        {% endif %}
    </div>
</div>
<div class="container mt-5">
    <h1 style="text-align: center; padding-bottom: 5rem;">Resep Berdasarkan Kategori</h1>
</div>
<div class="col-lg-12 mb-5">
    <div class="row justify-content-center">
        {% for kategori in list_kategori %}
            <div class="col-auto mb-3">
                <a class="link-spesifik" style="color:black" href="{{ kategori.get_absolute_url }}">
                    <div class="card">
                        {% if kategori.nama == "Ayam" %}
                            <img class="card-img-top" src="{% static 'Ayam.jpg' %}" alt="Ayam">
                            <div class="card-body" style="text-align: center;">
                                <p class="card-text">{{ kategori.nama }}</p>
                            </div>
                        {% elif kategori.nama == "Daging" %}
                            <img class="card-img-top" src="{% static 'Daging.jpg' %}" alt="Daging">
                            <div class="card-body" style="text-align: center;">
                                <p class="card-text">{{ kategori.nama }}</p>
                            </div>
                        {% elif kategori.nama == "Seafood" %}
                            <img class="card-img-top" src="{% static 'Seafood.jpg' %}" alt="Seafood">
                            <div class="card-body" style="text-align: center;">
                                <p class="card-text">{{ kategori.nama }}</p>
                            </div>
                        {% elif kategori.nama == "Tahu - Tempe - Telur" %}
                            <img class="card-img-top" src="{% static 'Tahu-Tempe-Telor.jpg' %}" alt="Tahu-Tempe-Telur">
                            <div class="card-body" style="text-align: center;">
                                <p class="card-text">{{ kategori.nama }}</p>
                            </div>
                        {% elif kategori.nama == "Sambal" %}
                            <img class="card-img-top" src="{% static 'Sambal.jpg' %}" alt="Sambal">
                            <div class="card-body" style="text-align: center;">
                                <p class="card-text">{{ kategori.nama }}</p>
                            </div>
                        {% elif kategori.nama == "Sayur" %}
                            <img class="card-img-top" src="{% static 'Sayur.jpg' %}" alt="Sayur">
                            <div class="card-body" style="text-align: center;">
                                <p class="card-text">{{ kategori.nama }}</p>
                            </div>
                        {% elif kategori.nama == "Dessert" %}
                            <img class="card-img-top" src="{% static 'Dessert.jpg' %}" alt="Dessert">
                            <div class="card-body" style="text-align: center;">
                                <p class="card-text">{{ kategori.nama }}</p>
                            </div>
                        {% elif kategori.nama == "Kue - Panganan Ringan" %}
                            <img class="card-img-top" src="{% static 'Kue.jpg' %}" alt="Kue">
                            <div class="card-body" style="text-align: center;">
                                <p class="card-text">{{ kategori.nama }}</p>
                            </div>
                        {% elif kategori.nama == "Minuman" %}
                            <img class="card-img-top" src="{% static 'Minuman.jpg' %}" alt="Minuman">
                            <div class="card-body" style="text-align: center;">
                                <p class="card-text">{{ kategori.nama }}</p>
                            </div>
                        {% else %}
                            <img class="card-img-top" src="{% static 'Lainnya.jpg' %}" alt="Lainnya">
                            <div class="card-body" style="text-align: center;">
                                <p class="card-text">{{ kategori.nama }}</p>
                            </div>
                        {% endif %}
                    </div>
                </a>
            </div>
        {% endfor %}
    </div>
</div>
{% endblock %}

kategori/templates/kategori_spesifik.html
{% extends 'base.html' %}
{% load static %}
{% block head %}
    <link rel="stylesheet" href="{% static 'kategori.css' %}">
{% endblock %}
{% block content %}
    <div class="container mt-5">
        <a href="{% url 'kategori:kategori' %}" class="btn btn-success"> < Kembali</a>
        <h1 style="text-align: center; padding-bottom: 5rem;">Kategori : {{ kategori }}</h1>
    </div>
    <div class="col-lg-12">
        <div class="row justify-content-center">
            {% if list_resep_by_kategori %}
                {% for resep in list_resep_by_kategori %}    
                        <div class="col-auto mb-3">
                            <a class="link-spesifik" style="color:black" href="{% url 'detailComment:detail' resep.nama %}">
                                <div class="card">
                                    {% if resep.foto %}
                                        <img class="card-img-top" src="{{ resep.foto.url }}" alt="{{ resep.nama }}">
                                    {% else %}
                                        <img class="card-img-top" src="{% static 'NoPhoto.jpg' %}" alt="Foto tanpa resep">
                                    {% endif %}
                                    <div class="card-body" style="text-align: center;">
                                        <p class="card-text">{{ resep.nama }}</p>
                                    </div>
                                </div>
                            </a>
                        </div>
                {% endfor %}
            {% else %}
                <br><br><br>
                <h5>Belum ada resep yang tersedia.</h5>
                <br><br><br>
            {% endif %}
        </div>
    </div>
{% endblock %}