homepage/urls.py
from django.urls import path
from . import views

app_name = "homepage"
urlpatterns = [
    path('', views.home, name='home'),
]

kategori/urls.py
from django.urls import path
from . import views

app_name = 'kategori'

urlpatterns = [
    path('', views.kategori, name="kategori"),
    path('<str:nama>/', views.spesifik, name="kategori_spesifik"),
    ]

kritiksaran/urls.py
from django.urls import path
from . import views

app_name = 'kritiksaran'

urlpatterns = [
    path('kritik-dan-saran/', views.kritik_submission_view, name="kritik_submission_view"),
    path('about-us/', views.about_us_view, name="about_us_view"),
    ]

makanminum/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('homepage.urls')),
    path('detail/', include('detailComment.urls')),
    path('resep_form/', include('tambahupdate.urls')),
    path('misc/', include('kritiksaran.urls')),
    path('kategori/', include('kategori.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

tambahupdate/urls.py
from django.urls import path
from . import views

app_name = 'tambahupdate'

urlpatterns = [
    path('tulis/', views.tulis, name="tulis"),
    path('perbarui/<int:pk>/', views.perbarui, name="perbarui"),
]

templates/base.html
{% load static %}
<!DOCTYPE html>
<html>
    <head>
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0, shrink-to-fit=no">
        <title>MakanMinum - Cari dan Berbagi Resep</title>
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css">
        <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
        <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js"></script>
        <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js"></script>
        <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js"></script>
        <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"></script>
        <link rel="stylesheet" href="{% static 'style.css' %}">
        <link rel="icon" href="{% static 'cutlery.png' %}" type="image/x-icon">
        {% block head %}{% endblock %}
    </head>
    <body>
        <nav class="navbar navbar-expand-lg navbar-dark sticky-top py-2">
            <a class="navbar-brand" href="{% url 'homepage:home' %}"><img src="{% static 'cutlery.png' %}" alt="cutlery" style="width: 0.8em; height: 0.8em; margin-bottom: 0.2em; margin-right: 0.2em;">MakanMinum</a>
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#collapsibleNavbar">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="collapsibleNavbar">
                <ul class="navbar-nav ml-auto">
                    <li class="nav-item" style="margin-right: 2em;">
                        <a class="nav-link" href="{% url 'homepage:home' %}">BERANDA</a>
                    </li>
                    <li class="nav-item " style="margin-right: 2em;">
                        <a class="nav-link" href="{% url 'kategori:kategori' %}">JELAJAHI RESEP</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'tambahupdate:tulis' %}">TULIS RESEP</a>
                    </li>
                </ul>
            </div>
        </nav>
        {% block body %}{% endblock %}
        <div id="content">
            {% block content %}{% endblock %}
        </div>
        <footer class="page-footer py-3">
            <div class="container-fluid">
                <div class="row">
                    <div class="col-lg-6 text-center text-lg-left" style="font-family: Grandstander, sans-serif; font-size: 22px;">© MakanMinum 2020</div>
                    <div class="col-lg-6 text-center text-lg-right">
                        <a href="{% url 'kritiksaran:about_us_view' %}" class="btn btn-outline-green px-3 py-1 mr-4">Tentang Kami</a>
                        <a href="{% url 'kritiksaran:kritik_submission_view' %}" class="btn btn-outline-green px-3 py-1">Kritik & Saran</a>
                    </div>
                </div>
            </div>
        </footer>
    </body>
</html>